ekf_se_odom:
  ros__parameters:
    frequency: 50.0
    sensor_timeout: 0.1
    two_d_mode: true
    publish_tf: true
    map_frame: map
    odom_frame: odom
    base_link_frame: base_link
    world_frame: odom

    # IMU input
    imu0: /imu/warthog
    imu0_config: [false, false, false,
                  true, true, true,
                  false, false, false]

    imu0_differential: false
    imu0_relative: true
    imu0_queue_size: 10

    # Odometry input
    odom0: /odom/wheel
    odom0_config: [true, true, false,
                   false, false, false,
                   true, true, true]
    odom0_differential: false
    odom0_relative: false
    odom0_queue_size: 10

    # Covariances for IMU and Odometry
    imu0_pose_covariance: [0.0, 0.0, 0.0,
                           0.0, 0.0, 0.0,
                           0.0, 0.0, 0.0]
    imu0_twist_covariance: [0.001, 0.0, 0.0,
                            0.0, 0.001, 0.0,
                            0.0, 0.0, 0.001]
    imu0_linear_acceleration_covariance: [0.01, 0.0, 0.0,
                                          0.0, 0.01, 0.0,
                                          0.0, 0.0, 0.01]

    odom0_pose_covariance: [0.001, 0.0, 0.0,
                            0.0, 0.001, 0.0,
                            0.0, 0.0, 0.001]
    odom0_twist_covariance: [0.001, 0.0, 0.0,
                             0.0, 0.001, 0.0,
                             0.0, 0.0, 0.001]
